name: Build
on: [workflow_dispatch]
jobs:
  ios:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Set Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
      - run: |
          npm install @capacitor/core@6 @capacitor/cli@6 @capacitor/ios@6
          
          # Настраиваем сервер внутри приложения, чтобы обойти черный экран
          cat <<EOF > capacitor.config.json
          {
            "appId": "com.ar4yc.tcoaal",
            "appName": "TCOAAL",
            "webDir": "www",
            "server": {
              "androidScheme": "https",
              "iosScheme": "capacitor",
              "allowNavigation": ["*"]
            }
          }
          EOF

          npx cap add ios
          find ios -name "project.pbxproj" -exec sed -i '' 's/13.0/14.0/g' {} +
          
          # Обязательно делаем copy, чтобы подтянулся новый конфиг
          npx cap sync ios
          
          xcodebuild archive -workspace ios/App/App.xcworkspace -scheme App -configuration Debug -destination 'generic/platform=iOS' -archivePath App.xcarchive CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" AD_HOC_CODE_SIGNING_ALLOWED=YES
          
          mkdir Payload && cp -r App.xcarchive/Products/Applications/App.app Payload/
          zip -r TCOAAL.ipa Payload
      - uses: actions/upload-artifact@v4
        with:
          name: TCOAAL-IPA
          path: TCOAAL.ipa
